"""Add seo_data field to pages

Revision ID: 9d50960c431b
Revises: 003
Create Date: 2026-01-23 20:55:10.292357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d50960c431b'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('seo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_pages_project_url_unique', table_name='pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pages_project_url_unique', 'pages', ['project_id', 'url'], unique=True)
    op.drop_column('pages', 'seo_data')
    # ### end Alembic commands ###

