"""Add example_prompts to projects

Revision ID: dd8df6cc9d20
Revises: 9d50960c431b
Create Date: 2026-01-23 21:14:01.746341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd8df6cc9d20'
down_revision: Union[str, None] = '9d50960c431b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('example_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'example_prompts')
    # ### end Alembic commands ###

